### ISSUE TITLE
Aragom

### ISSUE THREAD

**Issue by shadydark** [aragon/dao-global-hackaton#23]
We are looking to bring together Data feeds for the DAO ecosystem to improve the accessibility of Data for the ecosystem.

We would like a joint feed of ETH DAOs on Aragon Client and DAOs on Harmony in one place for teams to begin better tracking the DAO ecosystem.

**Comment by githubdoramon** [comment]
This one -> https://github.com/aragon/dao-global-hackaton/issues/14
